project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "The Best US State"
  author:
    - Youjia Li (yl5542)
    - Allan Chong (ac5439)
  repo-url: https://github.com/achong2001/BestState
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


