# Conclusion

>From our overall analysis of our graphs, we conclude that New Hampshire provides the best overall enviornment for any new homeowner. From our final two biplots, we showcased how this state would great benefit their immediate needs. Furthermore, from our overall biplot, we see that New Hampshire is one of the states with the highest rate of seniors residing, which makes it a much more friendly enviornment for other seniors. With a relatively low population, they have nearly double the amount of seniors than children living there, which further supports our main takeaway. Another key takeaway was that the Southern region and states typically performed the worst in our graphs with low income, high gini, and poor health and safety levels. This means that better institution needs to be inplace for these states to provide as high quality of living as the other states.
>One of our main points of argument was the fact that D.C was included in the southern region, where we based these regions off of CDC's grouping of states. We believe their data reflects more of the states in the Northeast. This means that our findings may be less pronounced in supporting our claim that the South provides an unstable enviornment for all new homeowners, where the data is more reflective of the other states as well.
>In the future, we hope to include more features that can better dictate which states are the best for all types of demographics of homeowners. Our data is heavily limited with no more than 10 features, but our study was mainly focused on factors that benefit our demographic of younger adulthood.
>We learned that many of our assumptions about features being correlated is not actually reflected by the data, such as mental health and employment. Our peers seem to heavily depend on finding an internship or job after graduation, which will heavily affect our mental health, but our overall data presents this as not so prevalent to all people.
