# Introduction

> For our project, we will mainly be answering the question of what are the best states in the U.S to reside in. Each of the 50 states has its own unique qualities, in which we will focus more on their pragmatic characteristics: safety, quality of life, and education. We searched for various types of socioeconomic and population data that could impact the decision making of house buyers. This decision making is typically performed subjectively based on specific features that house buyers will prioritize when searching for a new state to live in. However, house buyers may vary, such as retirees, young couples, and families with kids, so we will create our own indicators that categorize features that those types of homeowners would prioritize to determine the best state to live in depending on their circumstances. Thus, we can delve into various other subquestions such as: Which state provides the safest environment? Which state provides the most secure future for the youth? Our question can also be answered objectively through the observation of trends in graphs for all of the variables to determine the overall best state to live in for any type of homeowner.

> We believe these questions are important to study because they will be relevant to us and our peers as our job search preferences also depend on the site location. As we transition to different stages of adulthood, this study will always be significant for us to maximize our opportunities. Furthermore, our discoveries from the quality of states would not only benefit individual households but also improve the general quality of life in the U.S as everyone will have a deeper understanding of the living options that best fit their livelihood. We will leverage the data visualization tools that we learned throughout this semester to transform our datasets into compelling narratives that display how states measure up to the conclusion of what are the best states in the U.S.
